name: QA
on:
  push:
    branches: [ "qa" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Directory Permission
        run: chmod -R 777 /home/kz8vi9h6efqu/public_html/qa/