# This is a basic workflow to help you get started with Actions

name: digitalocean-pull-and-setup-env

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
    branches: [ "qa" ]
  # pull_request:
  #   branches: [ $default-branch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # SSH into digitalocean droplet
      - name: executing remote ssh commands using password
        uses: filmycart/nachiyartraders@qa
        with:
          directory: /home/kz8vi9h6efqu/public_html/qa
          host: ${{ secrets.github.com }}
          username: ${{ secrets.filmycart }}
          key: ${{ secrets.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 }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
