# name: QA
# on:
#   push:
#     branches: [ "qa" ]
#     #paths: ["home/kz8vi9h6efqu/public_html/qa/**"]
# permissions:
#   contents: write
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Copy files
#           run: |
#             git config --global user.name "filmycart"
#             git config --global user.email "filmycartin@gmail.com"
#             rsync -r --exclude=.git --exclude=.github
#       - name: Copy .env
#           run: php -r "file_exists('.env') || copy('.env.example', '.env');"
#       - name: Directory Permission
#           run: chmod -R 777 storage  
# step-deploy-prod:
#   stage: deploy
#   only:
#     - production
#   script:
#     - git checkout production
#     - git pull
#   environment: production
#   when: manual

  # jobs:
  #   script:
  #     - git pull qa
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Copy .env
  #       run: php -r "file_exists('.env') || copy('.env.example', '.env');"
  #     - name: Directory Permission
  #       run: chmod -R 777 storage
  # copy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout qa
  #       uses: actions/checkout@v4
  #       with:
  #         ref: qa
  #     - name: Copy files
  #         run: |
  #           git config --global user.name "filmycart"
  #           git config --global user.email "filmycartin@gmail.com"
  #           rsync -r --exclude=.git --exclude=.github
  #           git checkout qa
  #           git pull origin qa                  
  
name: Copy files to another branch
on:
    push:
        branches:
            - qa
    workflow_dispatch:
permissions:
    contents: write
    pages: write
    id-token: write
concurrency:
    group: "pages"
    cancel-in-progress: false
jobs:
    copy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout qa
              uses: actions/checkout@v4
              with:
                  ref: qa
            - name: Copy files to server
              run: |
                  git config --global user.name "filmycart"
                  git config --global user.email "filmycartin@gmail.com"
                  rsync -r --exclude=.git
                  git fetch
                  git checkout qa
                  git pull origin qa
                working-directory: /home/kz8vi9h6efqu/public_html/qa
     


        # Copy the repository to the directory on the server/VPS used for the application
      # - name: Copy dist to VPS
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     port: ${{ secrets.SSH_PORT }}
      #     key: ${{ secrets.SSH_KEY }}
      #     # Selecting all folders except "node_modules"
      #     source: ".,!node_modules"
      #     # The path is based on the directory where the user logged into the server starts
      #     target: "~/app/gobarber-backend"