name: QA
on:
  push:
    branches: [ "qa" ]
    #paths: ["home/kz8vi9h6efqu/public_html/qa/**"]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Directory Permission
        run: chmod -R 777
  # copy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout qa
  #       uses: actions/checkout@v4
  #       with:
  #       ref: qa
  #     - name: Copy files
  #       run: |
  #         git config --global user.name "filmycart"
  #         git config --global user.email "filmycartin@gmail.com"
  #         rsync -r --exclude=.git --exclude=.github
  #         git checkout qa
  #         git pull origin qa                  
  